default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-airflow
      user: airflowuser
      pass: pssd
      port: 5432
      dbname: dbtdb
      schema: dbt
      threads: 4