version: 2

sources:
  - name: instacart_raw_data
    database: dbtdb # Tell dbt to look for the source in the "raw" database
    schema: dbt_raw_data # You wouldn't put your source data in public, would you?
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: products
      - name: order_products__train
      - name: order_products__prior

models:
  - name: clean_orders
    description: One record per customer
    columns:
    - name: "(order_id || '-' || user_id)"
      description: Primary key
      tests:
        - unique
        - not_null
    # Uncomment me to fail
    # - name: "days_since_prior_order"
    #   description: Must have days since prior order
    #   tests:
    #     - not_null