#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS $AIRFLOW_SCHEMA AUTHORIZATION $POSTGRES_USER;
	
	CREATE DATABASE $DBT_POSTGRES_DB;
	GRANT ALL PRIVILEGES ON DATABASE $DBT_POSTGRES_DB TO $POSTGRES_USER;

	SET datestyle = "ISO, DMY";
EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DBT_POSTGRES_DB" <<-EOSQL

	CREATE SCHEMA IF NOT EXISTS $DBT_DBT_SCHEMA AUTHORIZATION $POSTGRES_USER;
	CREATE SCHEMA IF NOT EXISTS $DBT_DBT_RAW_DATA_SCHEMA AUTHORIZATION $POSTGRES_USER;
	
	SET datestyle = "ISO, DMY";
EOSQL


